### ISSUE TITLE
How can I go to specified page by default in react-native-viewpager?

### ISSUE THREAD

**Issue by h3l** [race604/react-native-viewpager#12]
In the below code

``` javascript
      <ViewPager
        style={{flex: 1}}
        dataSource={this.state.dataSource}
        renderPage={this._renderPage}
        autoPlay={false}/>
    );
```

I want have a attribute to control the index in view pager, such as initialPageNum.

**Comment by timzaak** [comment]
#8 may help you

**Comment by h3l** [comment]
@timzaak thank you, i just have a glance at ViewPager.js.
it seems use ViewPager.goToPage will have animate, but I don't want have any animate.

But still thank you, and I will have a try with ViewPager.goToPage

**Comment by race604** [comment]
I will add api to set current page.

**Comment by h3l** [comment]
@race604 hi there,
I have made some adjustment on react-native-viewpager, i can't read the source totally ,but I just remove the animation in `movePage`, and I have a commit here https://github.com/h3l/react-native-viewpager/commit/3e2ec1f6e47c9fc94fe4843713209d006b472415, but it just works, not beautiful, so, could you have more constructive suggestion.

**Comment by race604** [comment]
Sorry for so late reply.
I have add API to do this: `goToPage(pageNumber, animate = true)`. If you don't want animation, you can call like this, `viewpager.gotoPage(page, false)`. That's very similar your solution @h3l .
