### ISSUE TITLE
When looping disabled, block sliding right on first page, and sliding left on last page.

### ISSUE THREAD

**Issue by yyalim** [race604/react-native-viewpager#14]
Hello, i don't want to slide beyond the edge when loop is closed. So, again i edited files ViewPage.js file under the node_modules. Here is my code;

``` javascript
// ViewScript.js line: 94
onPanResponderMove: (e, gestureState) => {
  var dx = gestureState.dx;
  var offsetX = -dx / this.state.viewWidth + this.state.childIndex;
  var currentPage = this.state.currentPage;
  var pageCount = this.props.dataSource.getPageCount();

  if(this.props.isLoop || (!(currentPage === 0 && offsetX < 0) && !(currentPage === (pageCount - 1) && offsetX > 1))){
    this.state.scrollValue.setValue(offsetX);
  }
},
```

Once again i know this is not a good idea. When i will run `npm install` my changes will be replaced. So I did forked your project and make the changes.

Do you think, it is a good idea?

**Comment by yyalim** [comment]
With little research I found that i can do what i want with ES2015 inheritance.

I extended `ViewPager` class and override `componentWillMount` method and my problem solved.

**Comment by kesha-antonov** [comment]
Thanks for sharing. It helped me.
