### ISSUE TITLE
page content above pager indicator

### ISSUE THREAD

**Issue by sahir** [race604/react-native-viewpager#157]
Wants to shift page content above pager indicator when page content is going in scroll.
Is there any flag or props for it.

![screenshot_20170705-173627](https://user-images.githubusercontent.com/452706/27863714-0b0343c4-61a9-11e7-8232-f6c275eaff77.png)

**Comment by sahir** [comment]
@BigPun86 @race604

**Comment by GarimaMathur07** [comment]
@BigPun86 @race604 is there any solution for it

**Comment by race604** [comment]
You mean ScrollView in ViewPager?

**Comment by sahir** [comment]
@race604 issue was fixed Thanks
