### ISSUE TITLE
rise up indicator, but the point of indicator from the left and not start in the middle, 

### ISSUE THREAD

**Issue by amibition521** [race604/react-native-viewpager#19]
I will rise indicator, but the point of indicator from the left and not start in the middle, 

render :function () {
    return (
        <ViewPager 
          style={this.props.style}
          dataSource={this.state.dataSource}
          renderPage={this._renderPage}
          onChangePage={this._onChangePage}
          isLoop={true}
          autoPlay={true}   
         renderPageIndicator={this.renderIndicator}/>  
    ); 
  },

  renderIndicator:function (){
    return <ViewPageIndicator/>
  },

tabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
      bottom:300,
  },

**Comment by race604** [comment]
I didn't quite understand your question. Maybe you can upload the screenshot here.

**Comment by yadaniyil** [comment]
@amibition521 maybe you should clarify the solution if you closing the issue?
