### ISSUE TITLE
shasum check failed ... 0.1.6

### ISSUE THREAD

**Issue by c10lns** [race604/react-native-viewpager#21]
terminal > npm install react-native-viewpager --save

npm ERR! shasum check failed for /var/folders/d4/xhw0fzps7d961t9xj0kfj_rm0000gn/T/npm-3396-44a3b066/registry.npmjs.org/react-native-viewpager/-/react-native-viewpager-0.1.6.tgz
npm ERR! Expected: 82f4543b87f6eb09036603ef27de2d14711e12f5
npm ERR! Actual:   a7182df26be5eb4731295519dd8f5054f60a2c69
npm ERR! From:     https://registry.npmjs.org/react-native-viewpager/-/react-native-viewpager-0.1.6.tgz

**Comment by race604** [comment]
This should be npm error. Please try again

**Comment by c10lns** [comment]
Failed again. But the following is OK
`npm install react-native-viewpager@0.1.5 --save`
