### ISSUE TITLE
RenderPage not being called

### ISSUE THREAD

**Issue by danvass** [race604/react-native-viewpager#41]
I have followed the samples provided to implement myself but the render page function isn't being called. The onChangePage function is working correctly but my console.log() is never being triggered inside the render page and as such not displaying anything. Any reason for this @race604? Also to mention I'm not using for my datasource an array of strings but an array of objects (ie. {data: '1', data2: 2'}) but even when I try it with an array of strings it still does not work.

**Comment by danvass** [comment]
I managed to get it working in a file on its own but when trying to implement into an existing component it fails to render the page. On the one by itself it calls the renderPage functionality N amount of times upon loading whereas on the one in the existing component it does not, despite being implemented exactly the same. Do you have any examples of implementing into a more complex component?

**Comment by race604** [comment]
Did you wrap `ViewPager` in flexible component, Can you past your main layout code here? Here is a more complex demo, I used this in a `ListView` in https://github.com/race604/ZhiHuDaily-React-Native

**Comment by danvass** [comment]
What do you mean by flexible component? I have one page where it is divided 
into
four different components (with flex setting) and inside one I placed the
ViewPager. I'm currently not at my laptop but I'll post the code soon and 
thanks
for the example.

**Comment by danvass** [comment]
@race604 this is basically what I am trying to do : https://gist.github.com/DVassilev/c48a5f7dc9ff20752f62 but it isn't working. When I do the exact same thing but make the ViewPager the only component works fine but as soon as it I have it inside other components the renderPage doesn't seem to get called and it doesn't do anything (although if I click the dots it will change the page). Any ideas?

**Comment by danvass** [comment]
@race604 after further testing I noticed that even if <ViewPager /> is by itself, if it surrounded by <View> it will not work and not call renderPage. I have to remove everything but the <ViewPager> component itself for it to work. This is very odd behaviour and am unsure what would cause it.

**Comment by race604** [comment]
I modified some code in your gist and made it works properly. It seems that the property `alignItems: 'center'` makes the layout work as mess.

**Comment by danvass** [comment]
Thanks so much, that solved it for me. Seems it has an issue with 
alignItems.
Really appreciate the feedback, great component.

**Comment by danvass** [comment]
@race604 How can I set the style of the parent component so that the items within it, including the viewpager, are vertically centered?

**Comment by webbin** [comment]
The parent view of viewpage with the style "aligItems" will make the layout in mess,I delete it and everything work well as usual.
