### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by freefly801213** [race604/react-native-viewpager#47]
node v5.9.0
npm 3.8.3
npm install react-native-viewpager --save
get the error    npm ERR! cb() never called!

**Comment by jeduan** [comment]
getting the same currently

**Comment by jeduan** [comment]
got around it by adding `"react-native-viewpager": "race604/react-native-viewpager#8a9ffb3"` to my `package.json`. Weirdly, installing `0.2.0` also worked.

**Comment by freefly801213** [comment]
@jeduan thanks, it's work.

**Comment by bosung90** [comment]
+1 Please make it work without the hack

**Comment by alvarovmz** [comment]
@jeduan thanks

**Comment by sdqyang** [comment]
getting the same currently
