### ISSUE TITLE
How to get Current Page as Variable

### ISSUE THREAD

**Issue by ghost** [race604/react-native-viewpager#52]
Hello,

i am currently working on a new Application in React Native. I used the React Native Viewpager. Everything works fine until now.

Here is my question:

I would like to get the complete amount of 'Pages' and the Index of the currently showing 'Page'. I want to add an Counter such as '5/100', so the User knows where he/she is in the 'List' of Pages.

Any Ideas for an good Solution to generate this counter??

Catch up
Alex

**Comment by foxcode7** [comment]
in sourcecode ViewPager.js
`getInitialState() {
    return {
      currentPage: this.props.currentPage,
      viewWidth: 0,
      scrollValue: new Animated.Value(0)
    };
  },`
but there is a bug. when i change page from right,it will change twice.

**Comment by ghost** [comment]
Thanks for the idea.

But I am not sure if that is the Solution for my Problem.

I would like to have the Viewpager as it is. Then I would like to load the app an see the View Pager with all the Data. For the first 'Image' in the Viewpager I would like to have a Text Component at the Top saying " 1 / 5", then I would like to swipe to the right to get the next Image Page in the Viewpager, if that Image is shown the Text Component should show "2 / 5" and so on. 

I tried your Idea, but instead of showing me the first Image, I didn't see anything.

Any Idea?

**Comment by parameshwar-ande** [comment]
Hi,

I'm having the same problem , not able to get current page. viewPager.getCurrentPage() always giving me zero. @alexanderniebuhr did you find any solution for your problem, if so can you please share the solution.
Thanks in advance.
