### ISSUE TITLE
Invalid prop `renderPageIndicator` of type `boolean`

### ISSUE THREAD

**Issue by lucasmreis** [race604/react-native-viewpager#6]
If I set `renderPageIndicator` to false, as in: 

```
<ViewPager
  renderPageIndicator={false}
  ( ... rest of attributes ... ) />
```

I get the following message:

> Warning: Failed propType: Invalid prop `renderPageIndicator` of type `boolean` supplied to `ViewPager`, expected `function`.

Even though `false` appears to be a valid value:

``` js
// from ViewPager.js, line 178
if (this.props.renderPageIndicator === false) {
  return null;
}
```

**Comment by race604** [comment]
Sorry, I forgot the boolean type declaration. Fixed

**Comment by lucasmreis** [comment]
Thank you! And congratulations for the library! :+1:
