### ISSUE TITLE
React-Navive 0.26.0 run failed

### ISSUE THREAD

**Issue by zhqchen** [race604/react-native-viewpager#61]
Requiring React API from react-native is now deprecated。
see：   https://github.com/facebook/react-native/releases/tag/v0.25.1

**Comment by kael777** [comment]
you can fix it use the pull request #59 #58

**Comment by Roconda** [comment]
+1, would love to see this implemented

**Comment by lesliesam** [comment]
Can't wait for the code fix. I fixed it in a copy of my own at "https://github.com/lesliesam/react-native-viewpager-es6". Feel free to use it as a temp solution.
