### ISSUE TITLE
 W/ReactNativeJS: 'Warning: flattenChildren(...): Encountered two children with the same key, `.$p_0`. Child keys must be unique; when two children share a key, only the first child will be used.'

### ISSUE THREAD

**Issue by hufeng** [race604/react-native-viewpager#7]
when only one img,

``` javascript
<ViewPager
  isLoop={true}
  autoPlay={true}
 renderPage={this._renderPage}
 dataSource={dataSource.cloneWithPages(this.state.data)}/>
```

it will show the warning message and img can not display.

So, i change isLoop and autoPlay {this.state.data.length > 1}

**Comment by race604** [comment]
Great, there is a bug if data length less than 2. I'll fix this later.

**Comment by hufeng** [comment]
thanks @race604 viewpager很赞。另外，从您的zhihu-rn-android中学到很多的知识。谢谢。

**Comment by zj-lin-zj** [comment]
Is there any update on this bug? Or would you give a direction on where the bug comes from?

**Comment by race604** [comment]
I failed to get time to fix the bug, maybe this week.
`ViewPager` shows 3 children all the time in _loop_ mode. If it has only 2 children, it shows like this `0, 1, 0`, child 0 shows 2 times. But in React, each child's key must be unique for performance issue.

**Comment by ziyang0621** [comment]
@race604 What if I have only 1 child? Does it mean the ViewPager require at least 2 children? Thanks.
