### ISSUE TITLE
variable ‘nextChildIdx’ Duplicate declaration

### ISSUE THREAD

**Issue by JustFavor** [race604/react-native-viewpager#77]
react-native-viewpager/ViewPager.js: Duplicate declaration "nextChildIdx"

**Comment by riten7** [comment]
ya i am too facing the same issue.. Duplicate declaration "nextChildldx"

**Comment by DavidSongzw** [comment]
This problem also occurs. @race604

**Comment by race604** [comment]
Sorry. Fixed this.
