### ISSUE TITLE
passing props to renderPageIndicator function

### ISSUE THREAD

**Issue by braco** [race604/react-native-viewpager#82]
@race604: why not pass props to the renderPageIndicator function itself?

https://github.com/race604/react-native-viewpager/blob/master/ViewPager.js#L228

currently

```
      return React.cloneElement(this.props.renderPageIndicator(), props);
```

suggested

```
      return React.cloneElement(this.props.renderPageIndicator(props), props);
```

which would allow the this.props.renderPageIndicator function to be more flexible in usage:

```
_renderPageIndicator = (props) => {
  return (<VIew thing={props.otherthing}>);
}
```

**Comment by race604** [comment]
**props** is passed to children from parent component, and you'll pass it back to back to parent by `renderPageIndicator(props)` api, that is not quite reasonable I think. In your example, you can do this directly in the parent component:

```
_renderPageIndicator = () => {
  return (<View thing={otherthing}>);
}
```

**Comment by braco** [comment]
True, but you don't have access to the the page attributes, since the function is run without any arguments. In other words, there is no access to the current page, total pages, etc. as one would expect in renderPageIndicator.

If the API stays the same, you might as well just skip the function entirely:

renderPageIndicator={Component}
