### ISSUE TITLE
npm install shasum check failed

### ISSUE THREAD

**Issue by inetfuture** [race604/react-native-viewpager#86]
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/aaron/.nvm/versions/node/v6.2.1/bin/node" "/Users/aaron/.nvm/versions/node/v6.2.1/bin/npm" "install" "react-native-viewpager"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3

npm ERR! shasum check failed for /var/folders/z5/_cwxrnzd7y7120346gkmsp240000gn/T/npm-11372-2fab2b04/registry.npmjs.org/react-native-viewpager/-/react-native-viewpager-0.2.11.tgz
npm ERR! Expected: 7fff6bacdf3e354040422ba62a5f4f66fd1003e1
npm ERR! Actual:   08b8dc86febd7cca08a4963d4f04d45cf9d7eb3a
npm ERR! From:     https://registry.npmjs.org/react-native-viewpager/-/react-native-viewpager-0.2.11.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron/wp/To-Business-Phone/npm-debug.log

**Comment by jacobcyl** [comment]
I get the same error:
```shell
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /var/folders/96/5bl0jmyx6kd0h64t22blyd8r0000gn/T/npm-13116-579616f7/registry.npmjs.org/react-native-viewpager/-/react-native-viewpager-0.2.13.tgz
npm ERR! Expected: 75e421ae90e89efcd77d2c077c0525382b7c39c5
npm ERR! Actual:   ef25cebb946db959c28c21f22d56104b3a2f3680
npm ERR! From:     https://registry.npmjs.org/react-native-viewpager/-/react-native-viewpager-0.2.13.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
